### ISSUE TITLE
ModuleNotFoundError: No module named 'web3'

### ISSUE THREAD

**Issue by Jor-Tech** [tlex/geth-exporter#5]
Getting this error:

```
-- Logs begin at Wed 2020-04-01 19:23:43 CEST. --
Aug 28 16:12:50 ethnode-c4abc6966 geth-exporter[267037]: ModuleNotFoundError: No module named 'web3'
Aug 28 16:12:50 ethnode-c4abc6966 systemd[1]: geth-exporter.service: Main process exited, code=exited, status=1/FAILURE
Aug 28 16:12:50 ethnode-c4abc6966 systemd[1]: geth-exporter.service: Failed with result 'exit-code'.
Aug 28 16:23:16 ethnode-c4abc6966 systemd[1]: Started Geth Exporter.
Aug 28 16:23:16 ethnode-c4abc6966 geth-exporter[267172]: Traceback (most recent call last):
Aug 28 16:23:16 ethnode-c4abc6966 geth-exporter[267172]:   File "/usr/local/bin/geth-exporter", line 10, in <module>
Aug 28 16:23:16 ethnode-c4abc6966 geth-exporter[267172]:     from web3 import Web3, RPCProvider
Aug 28 16:23:16 ethnode-c4abc6966 geth-exporter[267172]: ModuleNotFoundError: No module named 'web3'
Aug 28 16:23:16 ethnode-c4abc6966 systemd[1]: geth-exporter.service: Main process exited, code=exited, status=1/FAILURE
Aug 28 16:23:16 ethnode-c4abc6966 systemd[1]: geth-exporter.service: Failed with result 'exit-code'.
```

I'm using different flags for --rpc and --rpcapi because geth --help tells me those are deprecated:
--rpc                               Enable the HTTP-RPC server (deprecated, use --http)
--rpcapi value                 API's offered over the HTTP-RPC interface (deprecated, use --http.api)

Currently running geth with these flags (in addition to Eth2 Medalla beacon and validator):
`ARGS="--goerli --datadir /home/ethereum/Goerli --metrics --metrics.expensive --pprof --maxpeers 100 --http --http.api db,eth,net,web3,personal"`

How do I get geth-exporter to work correctly without the web3 Module error?

**Comment by Jor-Tech** [comment]
installed web3 with 'pip3 install web3' and am now getting new error:

```
-- Logs begin at Wed 2020-04-01 19:23:43 CEST. --
Aug 28 16:23:16 ethnode-c4abc6966 geth-exporter[267172]: ModuleNotFoundError: No module named 'web3'
Aug 28 16:23:16 ethnode-c4abc6966 systemd[1]: geth-exporter.service: Main process exited, code=exited, status=1/FAILURE
Aug 28 16:23:16 ethnode-c4abc6966 systemd[1]: geth-exporter.service: Failed with result 'exit-code'.
Aug 28 16:44:59 ethnode-c4abc6966 systemd[1]: Started Geth Exporter.
Aug 28 16:45:01 ethnode-c4abc6966 geth-exporter[267849]: Traceback (most recent call last):
Aug 28 16:45:01 ethnode-c4abc6966 geth-exporter[267849]:   File "/usr/local/bin/geth-exporter", line 10, in <module>
Aug 28 16:45:01 ethnode-c4abc6966 geth-exporter[267849]:     from web3 import Web3, RPCProvider
Aug 28 16:45:01 ethnode-c4abc6966 geth-exporter[267849]: ImportError: cannot import name 'RPCProvider' from 'web3' (/home/ethereum/.local/lib/python3.8/site-packages/web3/__init__.py)
Aug 28 16:45:02 ethnode-c4abc6966 systemd[1]: geth-exporter.service: Main process exited, code=exited, status=1/FAILURE
Aug 28 16:45:02 ethnode-c4abc6966 systemd[1]: geth-exporter.service: Failed with result 'exit-code'.
```

**Comment by Jor-Tech** [comment]
Create a separate user "geth-exporter" to execute the systemdaemon, error changed to:

`ImportError: cannot import name 'RPCProvider' from 'web3' (/usr/local/lib/python3.8/dist-packages/web3/__init__.py)`

**Comment by tlex** [comment]
I'm sorry, I'm not maintaining this project anymore, since I'm not running my own Etherium node anymore. I'm accepting merge requests though.

**Comment by Jor-Tech** [comment]
It's fine, already forgot about it, think it got fixed some how, don't remember how or what did the trick. Probably user error from my side. Running an Eth node on a Raspberry Pi 4 for some months without issues now.

Thanks for the reply anyway :)

**Comment by tlex** [comment]
Thanks for the feedback. I'm closing this then :smiley:
